replicaCount: 1

image:
  repository: hub.nasajon.com.br/secretic
  pullPolicy: Always
  tag: "{{ TAG }}"

imagePullSecrets: 
  - name: hub
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: 
  runAsUser: 1000
  runAsGroup: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  privileged: false

service:
  type: ClusterIP
  port: 80
  containerPort: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx-external
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
  - host: priv.nasajon.com.br
    paths:
      - path: /
        pathType: ImplementationSpecific
  tls:
    - secretName: priv-tls
      hosts:
        - priv.nasajon.com.br

configMap:
  create: true
  name: "secretic"
  data:
    APP_NAME: "Laravel"
    APP_ENV: "production"
    APP_DEBUG: "true"
    APP_URL: "https://priv.nasajon.com.br"

    LOG_CHANNEL: "stack"
    LOG_DEPRECATIONS_CHANNEL: "null"
    LOG_LEVEL: "debug"

    DB_CONNECTION: "mysql"
    # Replace to DB_HOST=mysql when run via `sail up`
    DB_HOST: "mysql.secretic"
    DB_PORT: "3306"
    DB_DATABASE: "secretic"

    BROADCAST_DRIVER: "log"
    CACHE_DRIVER: "file"
    FILESYSTEM_DISK: "local"
    QUEUE_CONNECTION: "sync"
    SESSION_DRIVER: "file"
    SESSION_LIFETIME: "120"


secret:
  create: true
  name: "secretic"
  data: 
    DB_USERNAME: "root"  

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
